# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "08a82974105ccf04199c0ce674ab42d7"
name = "theme-app-extensions-demo"
handle = "theme-app-extensions-demo"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "nagata-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
